###
GET http://localhost:8080/prices
  ?date=2020-06-14T10:00:00
  &productId=35455
  &brandId=1

Content-Type: application/json
Accept: application/json

###
GET http://localhost:8080/prices
  ?date=2020-06-14T16:00:00
  &productId=35455
  &brandId=1

Content-Type: application/json
Accept: application/json

###
GET http://localhost:8080/prices
  ?date=2020-06-14T21:00:00
  &productId=35455
  &brandId=1

Content-Type: application/json
Accept: application/json

###
GET http://localhost:8080/prices
  ?date=2020-06-15T10:00:00
  &productId=35455
  &brandId=1

Content-Type: application/json
Accept: application/json

###
GET http://localhost:8080/prices
  ?date=2020-06-16T21:00:00
  &productId=35455
  &brandId=1

Content-Type: application/json
Accept: application/json

###
GET http://localhost:8080/prices
  ?date=2020-06-16T21:00:00
  &productId=35455
  &brandId=2

Content-Type: application/json
Accept: application/json

----------------------------------------------
###
curl --request GET \
  --url 'http://localhost:8080/prices?date=2020-06-14T10%3A00%3A00&productId=35455&brandId=1' \
  --header 'user-agent: vscode-restclient' \
  --data 'Content-Type: application/jsonAccept: application/json'

###
curl --request GET \
  --url 'http://localhost:8080/prices?date=2020-06-14T16%3A00%3A00&productId=35455&brandId=1' \
  --header 'user-agent: vscode-restclient' \
  --data 'Content-Type: application/jsonAccept: application/json'

###
curl --request GET \
  --url 'http://localhost:8080/prices?date=2020-06-14T21%3A00%3A00&productId=35455&brandId=1' \
  --header 'user-agent: vscode-restclient' \
  --data 'Content-Type: application/jsonAccept: application/json'

###
curl --request GET \
  --url 'http://localhost:8080/prices?date=2020-06-15T10%3A00%3A00&productId=35455&brandId=1' \
  --header 'user-agent: vscode-restclient' \
  --data 'Content-Type: application/jsonAccept: application/json'

###
curl --request GET \
  --url 'http://localhost:8080/prices?date=2020-06-16T21%3A00%3A00&productId=35455&brandId=1' \
  --header 'user-agent: vscode-restclient' \
  --data 'Content-Type: application/jsonAccept: application/json'

###
curl --request GET \
  --url 'http://localhost:8080/prices?date=2020-06-16T21%3A00%3A00&productId=35455&brandId=2' \
  --header 'user-agent: vscode-restclient' \
  --data 'Content-Type: application/jsonAccept: application/json----------------------------------------------'
