spring:
  datasource:
    url: jdbc:h2:mem:db;MODE=MSSQLServer;DATABASE_TO_UPPER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  h2:
    console.enabled: true

server:
  error:
    include-message: always
    include-stacktrace: on-param

springdoc:
  show-actuator: true